# Generated by Django 4.1.7 on 2023-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('DOB', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
